/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;


import Enum.StatusAsuransi;
import Service.NasabahService;
import Service.PolisService;
import Asuransi.AsuransiJiwa;
import Asuransi.AsuransiKesehatan;
import Model.Polis;

public class KelolaPolis extends javax.swing.JFrame {
    
    private NasabahService nasabahService;
    private PolisService polisService;
    private Polis polisTerpilih;
    private DefaultTableModel tableModel;
    

    
    public KelolaPolis(NasabahService nasabahService, PolisService polisService) {
        this.nasabahService = nasabahService;
        this.polisService = polisService;
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        initTable();
        loadPolis();
        
        txtIdPolis.setEditable(false);
        txtNama.setEditable(false);
        txtJenisPolis.setEditable(false);
        txttanggalMulai.setEditable(false);
        cmbStatus.setModel(
    new DefaultComboBoxModel<>(new String[]{"AKTIF", "NONAKTIF"})
);
       
   
    }
    
    private void initTable() {
    tableModel = new DefaultTableModel(
        new Object[]{
            "ID Polis",
            "ID Nasabah",
            "Nama",
            "Jenis Asuransi",
            "Premi",
            "Detail",
            "Status",
            "Tanggal Mulai",
            "Tanggal Selesai"
        },
        0
    );

    tblPolis.setModel(tableModel);
    }
    private void loadPolis() {
    tableModel.setRowCount(0);

    for (Polis p : polisService.getAllPolis()) {

       
        if (p.getNasabah() == null || p.getAsuransi() == null) {
            continue;
        }

        String jenisAsuransi =
            (p.getAsuransi() instanceof AsuransiJiwa)
                ? "Asuransi Jiwa"
                : "Asuransi Kesehatan";

        String detail =
            (p.getAsuransi() instanceof AsuransiJiwa)
                ? String.valueOf(((AsuransiJiwa) p.getAsuransi()).getSantunan())
                : ((AsuransiKesehatan) p.getAsuransi()).getJenisLayanan();

        tableModel.addRow(new Object[]{
            p.getIdPolis(),
            p.getNasabah().getIdNasabah(),
            p.getNasabah().getNama(),
            jenisAsuransi,
            p.getAsuransi().getPremi(),
            detail,
            p.getAsuransi().getStatus(),
            p.getTanggalMulai(),
            p.getTanggalAkhir()
        });
    }

    }
    private void resetForm() {
    txtIdPolis.setText("");
    txtNama.setText("");
    txtJenisPolis.setText("");
    txtPremi.setText("");
    txtSantunan.setText("");
    txttanggalMulai.setText("");
    txtTanggalSelesai.setText("");
    cmbStatus.setSelectedIndex(0);
    txtSantunan.setEnabled(false);
    polisTerpilih = null;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolis = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdPolis = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtJenisPolis = new javax.swing.JTextField();
        txtPremi = new javax.swing.JTextField();
        txtSantunan = new javax.swing.JTextField();
        txttanggalMulai = new javax.swing.JTextField();
        txtTanggalSelesai = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnPilih = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kelola Polis");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(923, 923, 923))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        tblPolis.setBackground(new java.awt.Color(255, 255, 255));
        tblPolis.setForeground(new java.awt.Color(0, 0, 0));
        tblPolis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Nasabah", "Nama", "Jenis Asuransi", "Premi", "Detail", "Status", "Tanggal Mulai", "Tanggal Selesai"
            }
        ));
        jScrollPane1.setViewportView(tblPolis);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Id Polis");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Premi");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Status");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Jenis Polis");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Santunan");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tanggal Mulai");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tanggal Selesai");

        txtIdPolis.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPolis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtIdPolis.setForeground(new java.awt.Color(0, 0, 0));
        txtIdPolis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPolisActionPerformed(evt);
            }
        });

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        txtNama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(0, 0, 0));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtJenisPolis.setBackground(new java.awt.Color(255, 255, 255));
        txtJenisPolis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtJenisPolis.setForeground(new java.awt.Color(0, 0, 0));
        txtJenisPolis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisPolisActionPerformed(evt);
            }
        });

        txtPremi.setBackground(new java.awt.Color(255, 255, 255));
        txtPremi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPremi.setForeground(new java.awt.Color(0, 0, 0));
        txtPremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPremiActionPerformed(evt);
            }
        });

        txtSantunan.setBackground(new java.awt.Color(255, 255, 255));
        txtSantunan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSantunan.setForeground(new java.awt.Color(0, 0, 0));
        txtSantunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSantunanActionPerformed(evt);
            }
        });

        txttanggalMulai.setBackground(new java.awt.Color(255, 255, 255));
        txttanggalMulai.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txttanggalMulai.setForeground(new java.awt.Color(0, 0, 0));
        txttanggalMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggalMulaiActionPerformed(evt);
            }
        });

        txtTanggalSelesai.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalSelesai.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTanggalSelesai.setForeground(new java.awt.Color(0, 0, 0));
        txtTanggalSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalSelesaiActionPerformed(evt);
            }
        });

        cmbStatus.setBackground(new java.awt.Color(255, 255, 255));
        cmbStatus.setForeground(new java.awt.Color(0, 0, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AKTIF", "NONAKTIF" }));

        btnPilih.setBackground(new java.awt.Color(255, 255, 255));
        btnPilih.setForeground(new java.awt.Color(0, 0, 0));
        btnPilih.setText("Pilih");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali.setForeground(new java.awt.Color(0, 0, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTanggalSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSantunan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJenisPolis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPremi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttanggalMulai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdPolis, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdPolis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtJenisPolis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPremi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSantunan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbStatus))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTanggalSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPolisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPolisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPolisActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtJenisPolisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisPolisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisPolisActionPerformed

    private void txtPremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPremiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPremiActionPerformed

    private void txtSantunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSantunanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSantunanActionPerformed

    private void txttanggalMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggalMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggalMulaiActionPerformed

    private void txtTanggalSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalSelesaiActionPerformed

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        int row = tblPolis.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this,
            "Pilih data polis terlebih dahulu",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    
    

    String idPolis = tableModel.getValueAt(row, 0).toString();
    polisTerpilih = polisService.cariPolisById(idPolis);

    if (polisTerpilih == null) return;
    
    txtIdPolis.setText(polisTerpilih.getIdPolis());
    txtNama.setText(polisTerpilih.getNasabah().getNama());
    txttanggalMulai.setText(polisTerpilih.getTanggalMulai());

    // Jenis polis
    if (polisTerpilih.getAsuransi() instanceof AsuransiJiwa) {
        txtJenisPolis.setText("Asuransi Jiwa");
    } else {
        txtJenisPolis.setText("Asuransi Kesehatan");
    }

    // Set ke form
    
    txtPremi.setText(String.valueOf(polisTerpilih.getAsuransi().getPremi()));
    txtTanggalSelesai.setText(polisTerpilih.getTanggalAkhir());
    cmbStatus.setSelectedItem(
    polisTerpilih.getAsuransi().getStatus().name()
);

    // KHUSUS ASURANSI JIWA
    if (polisTerpilih.getAsuransi() instanceof AsuransiJiwa) {
        txtSantunan.setEnabled(true);
        txtSantunan.setText(
            String.valueOf(((AsuransiJiwa) polisTerpilih.getAsuransi()).getSantunan())
        );
    } else {
        txtSantunan.setText("-");
        txtSantunan.setEnabled(false);
    }
    }//GEN-LAST:event_btnPilihActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new Dashboard(nasabahService, polisService);
            dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (polisTerpilih == null) {
    JOptionPane.showMessageDialog(
        this,
        "Pilih polis terlebih dahulu",
        "Peringatan",
        JOptionPane.WARNING_MESSAGE
    );
    return;
}

try {
    // Update premi
    Double premi = Double.parseDouble(txtPremi.getText());
    polisTerpilih.getAsuransi().setPremi(premi);

    // Update status
    String statusStr = cmbStatus.getSelectedItem().toString();
    StatusAsuransi status = StatusAsuransi.valueOf(statusStr);
    polisTerpilih.getAsuransi().setStatus(status);

    // Update tanggal
    polisTerpilih.setTanggalAkhir(txtTanggalSelesai.getText());

    // Khusus Asuransi Jiwa
    if (polisTerpilih.getAsuransi() instanceof AsuransiJiwa) {
        Double santunan =
            Double.parseDouble(txtSantunan.getText());
        ((AsuransiJiwa) polisTerpilih.getAsuransi())
            .setSantunan(santunan);
    }

    // SIMPAN KE FILE
    polisService.saveData();

    JOptionPane.showMessageDialog(
        this,
        "Data polis berhasil diperbarui",
        "Sukses",
        JOptionPane.INFORMATION_MESSAGE
    );

    loadPolis(); // refresh tabel
    resetForm();

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(
        this,
        "Premi / Santunan harus angka",
        "Error",
        JOptionPane.ERROR_MESSAGE
    );
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       resetForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaPolis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaPolis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaPolis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaPolis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        NasabahService nasabahService = new NasabahService();
        PolisService polisService = new PolisService(nasabahService);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaPolis(nasabahService, polisService).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPolis;
    private javax.swing.JTextField txtIdPolis;
    private javax.swing.JTextField txtJenisPolis;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPremi;
    private javax.swing.JTextField txtSantunan;
    private javax.swing.JTextField txtTanggalSelesai;
    private javax.swing.JTextField txttanggalMulai;
    // End of variables declaration//GEN-END:variables
}
